defaults:
  - logger: logger
  - arch: anakin
  - system: direct_backprop/ff_direct_backprop
  - network: mlp_direct_backprop
  - env: differentiable/acrobot
  - _self_

hydra:
  searchpath:
    - file://stoix/configs
